raise NameError("This is a manually raised exception!")
